version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - PORT=3000
        depends_on: 
            - mongo
    mongo:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: passw0rd
        volumes: 
            - mongo-db:/data/db
    redis:
        image: redis
volumes:
    mongo-db:
